<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <NoWarn>$(NoWarn);NU1510</NoWarn>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="input.css" />
    <Content Include="paket.references" />
    <Content Update="package.json" CopyToPublishDirectory="Never" />
    <Content Update="package-lock.json" CopyToPublishDirectory="Never" />
    <Compile Include="src/Infrastructure.fs" />
    <Compile Include="src/Config.fs" />
    <Compile Include="src/Consent.fs" />
    <Compile Include="src/Telemetry.fs" />
    <Compile Include="src/Services.fs" />
    <Compile Include="src/Articles/Article.fs" />
    <Compile Include="src/Common/View.fs" />
    <Compile Include="src/Common/Handler.fs" />
    <Compile Include="src/Articles/Shared.fs" />
    <Compile Include="src/Articles/Posts/FSharpSemanticKernel.fs" />
    <Compile Include="src/Articles/Posts/PersonalInfrastructure.fs" />
    <Compile Include="src/Articles/Posts/DevelopmentEnvironment.fs" />
    <Compile Include="src/Articles/Catalog.fs" />
    <Compile Include="src/Articles/View.fs" />
    <Compile Include="src/Articles/Handler.fs" />
    <Compile Include="src/Index/View.fs" />
    <Compile Include="src/Index/Handler.fs" />
    <Compile Include="src/Program.fs" />
  </ItemGroup>
  <Import Project="..\..\.paket\Paket.Restore.targets" />
</Project>